

/*
 * Filename: swc_remote.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_remote.h"
#include "WatchDog.h"


/* USER CODE START SWC_REMOTE_INCLUDE */
static boolean_t HandBrake=0;

/* Interrupt service routine for UART */
CY_ISR_PROTO(HandBrake_Interrupt);

/* USER CODE END SWC_REMOTE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */



/*
* component: swc_Remote
* cycletime: 10
* description: Joystick Runnable
* events: 
* name: REMOTE_Joystick_run
* shortname: Joystick
* signalIN: 
* signalOUT: so_Joystick
* task: tsk_IO
*/
void REMOTE_Joystick_run(RTE_event ev){

    /* USER CODE START REMOTE_Joystick_run */
    SC_JOYSTICK_data_t Joystick_Signal;
    if (HandBrake)
    {
        Joystick_Signal.x=0;
        Joystick_Signal.y=0;
        RTE_SC_JOYSTICK_set(&SO_JOYSTICK_signal, Joystick_Signal);
        UART_PutString("Hand Brake is On ");  
    }
    
    else{
    // Read Joystick signal from the joystick driver.
    if ( RC_SUCCESS != RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal))
    {
        UART_PutString("Joystick Data Not updated ");        
    }
    }
    // Signal that the device is alive by setting bit 0 in the watchdog status register
    WD_Alive(0);
    /* USER CODE END REMOTE_Joystick_run */
}


/* USER CODE START SWC_REMOTE_FUNCTIONS */
/* Interrupt service routine for Button */
CY_ISR(HandBrake_Interrupt)
{
    /* Read the received byte from UART and store it in Recived_Byte */
    HandBrake =~HandBrake;
    
}
/* USER CODE END SWC_REMOTE_FUNCTIONS */

