

/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "WatchDog.h"


/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
* component: swc_Engine
* cycletime: 100
* description: Runnable
* events: 
* name: ENGINE_Setpoint_run
* shortname: Setpoint
* signalIN: so_Target_Speed
* signalOUT: so_Control_Speed
* task: tsk_IO
*/
void ENGINE_Setpoint_run(RTE_event ev){

    /* USER CODE START ENGINE_Setpoint_run */
        
    // Set the control speed to be the same as the target speed
    SC_SPEED_data_t ControlSpeed;
    
    // Write the Engine Signal Value Green Led, The Green Led will indicate the control speed.
    if (RTE_SC_SPEED_getAge(&SO_TARGET_SPEED_signal) <MAX_AGE) {
    
        // Get the target speed from the signal object
        SC_SPEED_data_t TargetSpeed = RTE_SC_SPEED_get(&SO_TARGET_SPEED_signal);
        
        // Set the control speed value to be the same as the target speed
        ControlSpeed.Value = TargetSpeed.Value;

    }
    else{
        ControlSpeed.Value = 0;
        UART_PutString("Target Data Not updated ");
    } 
        
    // Set the control speed signal
    RTE_SC_SPEED_set(&SO_CONTROL_SPEED_signal, ControlSpeed);
    
    // Push the control speed signal to the port
    RTE_SC_SPEED_pushPort(&SO_CONTROL_SPEED_signal);
    
    // Signal that the device is alive by setting bit 2 in the watchdog status register
    WD_Alive(2);
    /* USER CODE END ENGINE_Setpoint_run */
}


/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

