
/*
 * Filename: swc_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_CONTROL
#define _H_DEFINE_SWC_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CONTROL_INCLUDES */

/* USER CODE END SWC_CONTROL_INCLUDES */



/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */


/*
* component: swc_control
* cycletime: 0
* description: Manual Driving function in first step
* events: ev_joystick_onData
* name: CONTROL_control_run
* shortname: control
* signalIN: so_Joystick
* signalOUT: so_Target_Speed
* task: tsk_control
*/
void CONTROL_control_run(RTE_event ev);


#endif