

/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "JoyStick.h"
#include <stdio.h>
#include "WatchDog.h"
/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */
void UART_Value(int x,int y)
{
    char str[10];
    sprintf(str,"(%d, %d) \r", x,y);
    UART_PutString(str);
}
/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
* component: swc_control
* cycletime: 0
* description: Manual Driving function in first step
* events: ev_joystick_onData
* name: CONTROL_control_run
* shortname: control
* signalIN: so_Joystick
* signalOUT: so_Target_Speed
* task: tsk_control
*/
void CONTROL_control_run(RTE_event ev){

    /* USER CODE START CONTROL_control_run */
    
    // Set the target speed to the x-axis value of the joystick signal
    SC_SPEED_data_t TargetSpeed;
    
    if (RTE_SC_JOYSTICK_getAge(&SO_JOYSTICK_signal) <MAX_AGE) {
        // Get the joystick signal
        SC_JOYSTICK_data_t Read_JoystickVal = RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal);
              
        // Value is bigger than 0, the speed signal (uint8_t) will be set to 2 x the joystick value.
        if (Read_JoystickVal.x>0) TargetSpeed.Value = 2*Read_JoystickVal.x;
        
        // If it is below or equal to 0,the engine value will be 0.
        else TargetSpeed.Value = 0;
        
        // Set Speed Signal
        RTE_SC_SPEED_set(&SO_TARGET_SPEED_signal, TargetSpeed);
        
        // Output the joystick values via UART
        UART_Value(TargetSpeed.Value , Read_JoystickVal.y);
    }
    else{
        UART_PutString("Joystick Data Not updated ");
        }
    
    // Signal that the device is alive by setting bit 1 in the watchdog status register
    WD_Alive(1);
    /* USER CODE END CONTROL_control_run */
}


/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

