
/*
 * Filename: swc_engine.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_ENGINE
#define _H_DEFINE_SWC_ENGINE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_INCLUDES */

/* USER CODE END SWC_ENGINE_INCLUDES */



/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */


/*
* component: swc_Engine
* cycletime: 100
* description: Runnable
* events: 
* name: ENGINE_Setpoint_run
* shortname: Setpoint
* signalIN: so_Target_Speed
* signalOUT: so_Control_Speed
* task: tsk_IO
*/
void ENGINE_Setpoint_run(RTE_event ev);


#endif