
/*
 * Filename: swc_brake.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_BRAKE
#define _H_DEFINE_SWC_BRAKE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKE_INCLUDES */

/* USER CODE END SWC_BRAKE_INCLUDES */



/* USER CODE START SWC_BRAKE_USERDEFINITIONS */

/* USER CODE END SWC_BRAKE_USERDEFINITIONS */


/*
* component: swc_Brake
* cycletime: 0
* description: to activate the brake lights
* events: ev_target_speed_onData
* name: BRAKE_Lights_run
* shortname: Lights
* signalIN: so_Target_Speed
* signalOUT: so_BreakLight
* task: tsk_control
*/
void BRAKE_Lights_run(RTE_event ev);


#endif