
/*
 * Filename: swc_remote.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_REMOTE
#define _H_DEFINE_SWC_REMOTE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_REMOTE_INCLUDES */

/* USER CODE END SWC_REMOTE_INCLUDES */



/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */


/*
* component: swc_Remote
* cycletime: 10
* description: Joystick Runnable
* events: 
* name: REMOTE_Joystick_run
* shortname: Joystick
* signalIN: 
* signalOUT: so_Joystick
* task: tsk_IO
*/
void REMOTE_Joystick_run(RTE_event ev);


#endif