

/*
 * Filename: swc_brake.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brake.h"
#include "WatchDog.h"


/* USER CODE START SWC_BRAKE_INCLUDE */

/* USER CODE END SWC_BRAKE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKE_USERDEFINITIONS */

/* USER CODE END SWC_BRAKE_USERDEFINITIONS */



/*
* component: swc_Brake
* cycletime: 0
* description: to activate the brake lights
* events: ev_target_speed_onData
* name: BRAKE_Lights_run
* shortname: Lights
* signalIN: so_Target_Speed
* signalOUT: so_BreakLight
* task: tsk_control
*/
void BRAKE_Lights_run(RTE_event ev){

    /* USER CODE START BRAKE_Lights_run */
    // Create a brake signal with the same value as the target speed
    SC_BREAK_data_t Brake_Signal;
    
    // Write the Brake Signal Value Red Led, The Red Led will indicate the Brake Output.
    if (RTE_SC_SPEED_getAge(&SO_TARGET_SPEED_signal) <MAX_AGE) {
    
    // Get the target speed signal
    SC_SPEED_data_t TargetSpeed = RTE_SC_SPEED_get(&SO_TARGET_SPEED_signal);
    
    // Set the Brake speed value to be the same as the target speed
    Brake_Signal.Value = TargetSpeed.Value;

    }
    else{
        Brake_Signal.Value = 0;
        UART_PutString("Target Speed Data Not updated ");
    }
    
       // Set the brake light signal
    RTE_SC_BREAK_set(&SO_BREAKLIGHT_signal, Brake_Signal);

    // Push the brake light signal to the port and write the brake light value to the RED LED
    if ( RC_SUCCESS != RTE_SC_BREAK_pushPort(&SO_BREAKLIGHT_signal))
    {
       UART_PutString("Invalid Brakelight data"); 
    }
    // Signal that the device is alive by setting bit 3 in the watchdog status register
    WD_Alive(3);
    /* USER CODE END BRAKE_Lights_run */
}


/* USER CODE START SWC_BRAKE_FUNCTIONS */

/* USER CODE END SWC_BRAKE_FUNCTIONS */

