
/*
 * Filename: tsk_io.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_IO
#define _H_DEFINE_TSK_IO

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_IO_INCLUDES */

/* USER CODE END TSK_IO_INCLUDES */



/*
* description: Contain all signals like remote, engine etc
* events: 
* mode: Cyclic
* name: tsk_IO
* shortname: IO
* signalpoolsRO: sp_Common
* signalpoolsRW: sp_Common
* tickEvent: 0
* timertickperiod: 1
*/
DeclareTask(tsk_io);


#endif