

/*
 * Filename: swc_hmi_display.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_hmi_display.h"



/* USER CODE START SWC_HMI_DISPLAY_INCLUDE */

/* USER CODE END SWC_HMI_DISPLAY_INCLUDE */


#include "sp_common_signal.h"

/* USER CODE START SWC_HMI_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_HMI_DISPLAY_USERDEFINITIONS */



/*
* component: swc_HMI_Display
* cycletime: 0
* description: Runnable
* events: ev_clock_signal_onData
* name: HMI_DISPLAY__run
* shortname: 
* signalIN: so_Clock_Signal
* signalOUT: so_HMI_Signal
* task: tsk_HMI
*/
void HMI_DISPLAY__run(RTE_event ev){
	
	/* USER CODE START HMI_DISPLAY__run */
	/*SC_CLOCK_SIGNAL_data_t Clock_Received_Signal = RTE_SC_CLOCK_SIGNAL_get(&SO_CLOCK_SIGNAL_signal);
    
    RTE_SC_CLOCK_SIGNAL_set(&SO_HMI_SIGNAL_signal, Clock_Received_Signal);
    
    if ( RC_SUCCESS != RTE_SC_CLOCK_SIGNAL_pushPort(&SO_HMI_SIGNAL_signal))
    {
        UART_LOG_PutString("Invalid HMI data"); 
    }*/
    /* USER CODE END HMI_DISPLAY__run */
}

/* USER CODE START SWC_HMI_DISPLAY_FUNCTIONS */

/* USER CODE END SWC_HMI_DISPLAY_FUNCTIONS */

