
/*
 * Filename: swc_button_read.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_BUTTON_READ
#define _H_DEFINE_SWC_BUTTON_READ

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BUTTON_READ_INCLUDES */

/* USER CODE END SWC_BUTTON_READ_INCLUDES */



/* USER CODE START SWC_BUTTON_READ_USERDEFINITIONS */

/* USER CODE END SWC_BUTTON_READ_USERDEFINITIONS */


/*
* component: swc_Button_Read
* cycletime: 50
* description: This runnable reads the data out of the buttons and send the event to the Clock control runnable
* events: 
* name: BUTTON_READ__run
* shortname: 
* signalIN: 
* signalOUT: so_Event_Signal
* task: tsk_IO
*/
void BUTTON_READ__run(RTE_event ev);


#endif