
/*
 * Filename: swc_hmi_display.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_HMI_DISPLAY
#define _H_DEFINE_SWC_HMI_DISPLAY

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_HMI_DISPLAY_INCLUDES */

/* USER CODE END SWC_HMI_DISPLAY_INCLUDES */



/* USER CODE START SWC_HMI_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_HMI_DISPLAY_USERDEFINITIONS */


/*
* component: swc_HMI_Display
* cycletime: 0
* description: Runnable
* events: ev_clock_signal_onData
* name: HMI_DISPLAY__run
* shortname: 
* signalIN: so_Clock_Signal
* signalOUT: so_HMI_Signal
* task: tsk_HMI
*/
void HMI_DISPLAY__run(RTE_event ev);


#endif