
/*
 * Filename: tsk_io.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_IO
#define _H_DEFINE_TSK_IO

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_IO_INCLUDES */

/* USER CODE END TSK_IO_INCLUDES */



/*
* description: This task Handles all the Input and output events
* events: 
* mode: Cyclic
* name: tsk_IO
* shortname: IO
* signalpoolsRO: sp_Common_Signal
* signalpoolsRW: sp_Common_Signal
* tickEvent: 0
* timertickperiod: 1
*/
DeclareTask(tsk_IO);


#endif