
/*
 * Filename: tsk_hmi.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_HMI
#define _H_DEFINE_TSK_HMI

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_HMI_INCLUDES */

/* USER CODE END TSK_HMI_INCLUDES */



/*
* description: This task shows the clock value on tft 
* events: 
* mode: Cyclic
* name: tsk_HMI
* shortname: HMI
* signalpoolsRO: sp_Common_Signal
* signalpoolsRW: sp_Common_Signal
* tickEvent: 0
* timertickperiod: 1
*/
DeclareTask(tsk_HMI);


#endif