
/*
 * Filename: tsk_clock_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_CLOCK_CONTROL
#define _H_DEFINE_TSK_CLOCK_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_CLOCK_CONTROL_INCLUDES */

/* USER CODE END TSK_CLOCK_CONTROL_INCLUDES */



/*
* description: This task handles the state machine of the Clock
* events: ev_event_signal_onData
* mode: Event
* name: tsk_Clock_Control
* shortname: Clock Control
* signalpoolsRO: sp_Common_Signal
* signalpoolsRW: sp_Common_Signal
* tickEvent: 0
* timertickperiod: 1
*/
DeclareTask(tsk_Clock_Control);


#endif