

/*
 * Filename: tsk_clock_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_clock_control.h"



/* USER CODE START TSK_CLOCK_CONTROL_INCLUDE */

/* USER CODE END TSK_CLOCK_CONTROL_INCLUDE */

#include "swc_clock_control.h"



/* USER CODE START TSK_CLOCK_CONTROL_USERDEFINITIONS */

/* USER CODE END TSK_CLOCK_CONTROL_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_clock_control[] = {
    { CLOCK_CONTROL__run, ev_event_signal_onData },  //This Runnable is oprating the state machine of the clock.
}; 
const uint16_t RTE_eventActivation_tsk_clock_control_size = sizeof (RTE_eventActivationTable_tsk_clock_control) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
* description: This task handles the state machine of the Clock
* events: ev_event_signal_onData
* mode: Event
* name: tsk_Clock_Control
* shortname: Clock Control
* signalpoolsRO: sp_Common_Signal
* signalpoolsRW: sp_Common_Signal
* tickEvent: 0
* timertickperiod: 1
*/
TASK(tsk_Clock_Control)
{
    EventMaskType ev = 0;
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_event_signal_onData);
        GetEvent(tsk_Clock_Control,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_CLOCK_CONTROL_TASKBOBY_PRE */

		/* USER CODE END TSK_CLOCK_CONTROL_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_clock_control, RTE_eventActivation_tsk_clock_control_size, ev);
		
		/* USER CODE START TSK_CLOCK_CONTROL_TASKBODY_POST */

		/* USER CODE END TSK_CLOCK_CONTROL_TASKBODY_POST */

        
    }
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_CLOCK_CONTROL_ISR */

/* USER CODE END TSK_CLOCK_CONTROL_ISR */

